apiVersion: v1
kind: Secret
metadata:
  name: modular-chatbot-secrets
  namespace: modular-chatbot
  labels:
    app: modular-chatbot
type: Opaque
data:
  # Base64 encoded secrets - replace with actual values
  # To encode: echo -n "your_secret_here" | base64
  OPENAI_API_KEY: eW91cl9vcGVuYWlfYXBpX2tleV9oZXJl  # your_openai_api_key_here
  SECRET_KEY: eW91cl9zZWNyZXRfa2V5X2hlcmU=  # your_secret_key_here
  JWT_SECRET: eW91cl9qd3Rfc2VjcmV0X2hlcmU=  # your_jwt_secret_here
  REDIS_PASSWORD: ""  # Empty for no password, or base64 encoded password

---
# TLS Secret for HTTPS (replace with your actual certificate)
apiVersion: v1
kind: Secret
metadata:
  name: chatbot-tls
  namespace: modular-chatbot
  labels:
    app: modular-chatbot
type: kubernetes.io/tls
data:
  # Replace with your actual base64 encoded certificate and key
  tls.crt: LS0tLS1CRUdJTi... # Base64 encoded certificate
  tls.key: LS0tLS1CRUdJTi... # Base64 encoded private key